% network defines
-define(I, /unsigned-integer).
-define(IL, /unsigned-little-integer).
-define(IB, /unsigned-big-integer).
-define(b, /bytes).
-define(f, :32/float-little).
-define(SH, :160?IL). % sha1
-define(Q, :64?IL). % quad
-define(L, :32?IL). % long
-define(W, :16?IL). % word
-define(WO, :16?IB). % word, big endian
-define(B, :8). %byte
