-define(cast_flag_none, 16#00000000).
-define(cast_flag_hidden_combatlog, 16#00000001).               % hide in combat log?
-define(cast_flag_unknown2, 16#00000002).
-define(cast_flag_unknown3, 16#00000004).
-define(cast_flag_unknown4, 16#00000008).
-define(cast_flag_unknown5, 16#00000010).
-define(cast_flag_ammo, 16#00000020).               % Projectiles visual
-define(cast_flag_unknown7, 16#00000040).               % !0x41 mask used to call CGTradeSkillInfo::DoRecast
-define(cast_flag_unknown8, 16#00000080).
-define(cast_flag_unknown9, 16#00000100).


-define(spell_failed_affecting_combat, 16#00).
-define(spell_failed_already_at_full_health, 16#01).
-define(spell_failed_already_at_full_mana, 16#02).
-define(spell_failed_already_being_tamed, 16#03).
-define(spell_failed_already_have_charm, 16#04).
-define(spell_failed_already_have_summon, 16#05).
-define(spell_failed_already_open, 16#06).
-define(spell_failed_more_powerful_spell_active, 16#07).
%-define(spell_failed_autotrack_interrupted, 16#08). old commented CAST_FAIL_FAILED = 8,-> 29
-define(spell_failed_bad_implicit_targets, 16#09).
-define(spell_failed_bad_targets, 16#0A).
-define(spell_failed_cant_be_charmed, 16#0B).
-define(spell_failed_cant_be_disenchanted, 16#0C).
-define(spell_failed_cant_be_prospected, 16#0D).
-define(spell_failed_cant_cast_on_tapped, 16#0E).
-define(spell_failed_cant_duel_while_invisible, 16#0F).
-define(spell_failed_cant_duel_while_stealthed, 16#10).
-define(spell_failed_cant_too_close_to_enemy, 16#11).
-define(spell_failed_cant_do_that_yet, 16#12).
-define(spell_failed_caster_dead, 16#13).
-define(spell_failed_charmed, 16#14).
-define(spell_failed_chest_in_use, 16#15).
-define(spell_failed_confused, 16#16).
-define(spell_failed_dont_report, 16#17).     % [-ZERO] need check
-define(spell_failed_equipped_item, 16#18).
-define(spell_failed_equipped_item_class, 16#19).
-define(spell_failed_equipped_item_class_mainhand, 16#1A).
-define(spell_failed_equipped_item_class_offhand, 16#1B).
-define(spell_failed_error, 16#1C).
-define(spell_failed_fizzle, 16#1D).
-define(spell_failed_fleeing, 16#1E).
-define(spell_failed_food_lowlevel, 16#1F).
-define(spell_failed_highlevel, 16#20).
%-define(spell_failed_hunger_satiated, 16#21).
-define(spell_failed_immune, 16#22).
-define(spell_failed_interrupted, 16#23).
-define(spell_failed_interrupted_combat, 16#24).
-define(spell_failed_item_already_enchanted, 16#25).
-define(spell_failed_item_gone, 16#26).
-define(spell_failed_enchant_not_existing_item, 16#27).
-define(spell_failed_item_not_ready, 16#28).
-define(spell_failed_level_requirement, 16#29).
-define(spell_failed_line_of_sight, 16#2A).
-define(spell_failed_lowlevel, 16#2B).
-define(spell_failed_skill_not_high_enough, 16#2C).
-define(spell_failed_mainhand_empty, 16#2D).
-define(spell_failed_moving, 16#2E).
-define(spell_failed_need_ammo, 16#2F).
-define(spell_failed_need_requires_something, 16#30).
-define(spell_failed_need_exotic_ammo, 16#31).
-define(spell_failed_nopath, 16#32).
-define(spell_failed_not_behind, 16#33).
-define(spell_failed_not_fishable, 16#34).
-define(spell_failed_not_here, 16#35).
-define(spell_failed_not_infront, 16#36).
-define(spell_failed_not_in_control, 16#37).
-define(spell_failed_not_known, 16#38).
-define(spell_failed_not_mounted, 16#39).
-define(spell_failed_not_on_taxi, 16#3A).
-define(spell_failed_not_on_transport, 16#3B).
-define(spell_failed_not_ready, 16#3C).
-define(spell_failed_not_shapeshift, 16#3D).
-define(spell_failed_not_standing, 16#3E).
-define(spell_failed_not_tradeable, 16#3F).     % rogues trying "enchant" other's weapon with poison
-define(spell_failed_not_trading, 16#40).     % CAST_FAIL_CANT_ENCHANT_TRADE_ITEM
-define(spell_failed_not_unsheathed, 16#41).     % yellow text
-define(spell_failed_not_while_ghost, 16#42).
-define(spell_failed_no_ammo, 16#43).
-define(spell_failed_no_charges_remain, 16#44).
-define(spell_failed_no_champion, 16#45).     % CAST_FAIL_NOT_SELECT
-define(spell_failed_no_combo_points, 16#46).
-define(spell_failed_no_dueling, 16#47).
-define(spell_failed_no_endurance, 16#48).
-define(spell_failed_no_fish, 16#49).
-define(spell_failed_no_items_while_shapeshifted, 16#4A).
-define(spell_failed_no_mounts_allowed, 16#4B).
-define(spell_failed_no_pet, 16#4C).
-define(spell_failed_no_power, 16#4D).     % CAST_FAIL_NOT_ENOUGH_MANA
-define(spell_failed_nothing_to_dispel, 16#4E).
-define(spell_failed_nothing_to_steal, 16#4F).
-define(spell_failed_only_abovewater, 16#50).     % CAST_FAIL_CANT_USE_WHILE_SWIMMING
-define(spell_failed_only_daytime, 16#51).
-define(spell_failed_only_indoors, 16#52).
-define(spell_failed_only_mounted, 16#53).
-define(spell_failed_only_nighttime, 16#54).
-define(spell_failed_only_outdoors, 16#55).
-define(spell_failed_only_shapeshift, 16#56).
-define(spell_failed_only_stealthed, 16#57).
-define(spell_failed_only_underwater, 16#58).     % CAST_FAIL_CAN_ONLY_USE_WHILE_SWIMMING
-define(spell_failed_out_of_range, 16#59).
-define(spell_failed_pacified, 16#5A).
-define(spell_failed_possessed, 16#5B).
%-define(spell_failed_reagents, 16#5C). [-ZERO] not in 1.12
-define(spell_failed_requires_area, 16#5D).     % CAST_FAIL_YOU_NEED_TO_BE_IN_XXX
-define(spell_failed_requires_spell_focus, 16#5E).     % CAST_FAIL_REQUIRES_XXX
-define(spell_failed_rooted, 16#5F).     % CAST_FAIL_UNABLE_TO_MOVE
-define(spell_failed_silenced, 16#60).
-define(spell_failed_spell_in_progress, 16#61).
-define(spell_failed_spell_learned, 16#62).
-define(spell_failed_spell_unavailable, 16#63).
-define(spell_failed_stunned, 16#64).
-define(spell_failed_targets_dead, 16#65).
-define(spell_failed_target_affecting_combat, 16#66).
-define(spell_failed_target_aurastate, 16#67).     % CAST_FAIL_CANT_DO_THAT_YET_2
-define(spell_failed_target_dueling, 16#68).
-define(spell_failed_target_enemy, 16#69).
-define(spell_failed_target_enraged, 16#6A).     % CAST_FAIL_TARGET_IS_TOO_ENRAGED_TO_CHARM
-define(spell_failed_target_friendly, 16#6B).
-define(spell_failed_target_in_combat, 16#6C).
-define(spell_failed_target_is_player, 16#6D).
-define(spell_failed_target_not_dead, 16#6E).
-define(spell_failed_target_not_in_party, 16#6F).
-define(spell_failed_target_not_looted, 16#70).     % CAST_FAIL_CREATURE_MUST_BE_LOOTED_FIRST
-define(spell_failed_target_not_player, 16#71).
-define(spell_failed_target_no_pockets, 16#72).     % CAST_FAIL_NOT_ITEM_TO_STEAL
-define(spell_failed_target_no_weapons, 16#73).
-define(spell_failed_target_unskinnable, 16#74).
-define(spell_failed_thirst_satiated, 16#75).
-define(spell_failed_too_close, 16#76).
-define(spell_failed_too_many_of_item, 16#77).
%-define(spell_failed_totems, 16#78).  % [-ZERO] not in 1.12
-define(spell_failed_training_points, 16#79).
-define(spell_failed_try_again, 16#7A).     % CAST_FAIL_FAILED_ATTEMPT
-define(spell_failed_unit_not_behind, 16#7B).
-define(spell_failed_unit_not_infront, 16#7C).
-define(spell_failed_wrong_pet_food, 16#7D).
-define(spell_failed_not_while_fatigued, 16#7E).
-define(spell_failed_target_not_in_instance, 16#7F).     % CAST_FAIL_TARGET_MUST_BE_IN_THIS_INSTANCE
-define(spell_failed_not_while_trading, 16#80).
-define(spell_failed_target_not_in_raid, 16#81).
-define(spell_failed_disenchant_while_looting, 16#82).
-define(spell_failed_prospect_while_looting, 16#83).
%-define(spell_failed_prospect_need_more, 16#85).
-define(spell_failed_target_freeforall, 16#85).
-define(spell_failed_no_edible_corpses, 16#86).
-define(spell_failed_only_battlegrounds, 16#87).
-define(spell_failed_target_not_ghost, 16#88).
-define(spell_failed_too_many_skills, 16#89).     % CAST_FAIL_YOUR_PET_CANT_LEARN_MORE_SKILLS
-define(spell_failed_cant_use_new_item, 16#8A).
-define(spell_failed_wrong_weather, 16#8B).     % CAST_FAIL_CANT_DO_IN_THIS_WEATHER
-define(spell_failed_damage_immune, 16#8C).     % CAST_FAIL_CANT_DO_IN_IMMUNE
-define(spell_failed_prevented_by_mechanic, 16#8D).     % CAST_FAIL_CANT_DO_IN_XXX
-define(spell_failed_play_time, 16#8E).     % CAST_FAIL_GAME_TIME_OVER
-define(spell_failed_reputation, 16#8F).
-define(spell_failed_min_skill, 16#90).
-define(spell_failed_unknown, 16#91).
-define(spell_cast_ok, 16#FF).      % custom value). don't must be send to client




-define(target_flag_self, 16#00000000).
-define(target_flag_unused1, 16#00000001).       %%< not used in any spells (can be set dynamically)
-define(target_flag_unit, 16#00000002).       %%< pguid
-define(target_flag_unused2, 16#00000004).       %%< not used in any spells (can be set dynamically)
-define(target_flag_unused3, 16#00000008).       %%< not used in any spells (can be set dynamically)
-define(target_flag_item, 16#00000010).       %%< pguid
-define(target_flag_source_location, 16#00000020).       %%< 3 float
-define(target_flag_dest_location, 16#00000040).       %%< 3 float
-define(target_flag_object_unk, 16#00000080).       %%< used in 7 spells only
-define(target_flag_unit_unk, 16#00000100).       %%< looks like self target (389 spells)
-define(target_flag_pvp_corpse, 16#00000200).       %%< pguid
-define(target_flag_unit_corpse, 16#00000400).       %%< 10 spells (gathering professions)
-define(target_flag_object, 16#00000800).       %%< pguid, 0 spells
-define(target_flag_trade_item, 16#00001000).       %%< pguid, 0 spells
-define(target_flag_string, 16#00002000).       %%< string, 0 spells
-define(target_flag_unk1, 16#00004000).       %%< 199 spells, opening object/lock
-define(target_flag_corpse, 16#00008000).       %%< pguid, resurrection spells
-define(target_flag_unk2, 16#00010000).       %%< pguid, not used in any spells (can be set dynamically)





-define(spellfamily_generic, 0).
-define(spellfamily_environment, 1). % EVENTS, HOLIDAys, mostly aura related spells
    % 2 - unused
-define(spellfamily_mage, 3).
-define(spellfamily_warrior, 4).
-define(spellfamily_warlock, 5).
-define(spellfamily_priest, 6).
-define(spellfamily_druid, 7).
-define(spellfamily_rogue, 8).
-define(spellfamily_hunter, 9).
-define(spellfamily_paladin, 10).
-define(spellfamily_shaman, 11).
    % 12 - unused
-define(spellfamily_potion, 13).












-define(spell_aura_none, 0).
-define(spell_aura_bind_sight, 1).
-define(spell_aura_mod_possess, 2).
-define(spell_aura_periodic_damage, 3).
-define(spell_aura_dummy, 4).
-define(spell_aura_mod_confuse, 5).
-define(spell_aura_mod_charm, 6).
-define(spell_aura_mod_fear, 7).
-define(spell_aura_periodic_heal, 8).
-define(spell_aura_mod_attackspeed, 9).
-define(spell_aura_mod_threat, 10).
-define(spell_aura_mod_taunt, 11).
-define(spell_aura_mod_stun, 12).
-define(spell_aura_mod_damage_done, 13).
-define(spell_aura_mod_damage_taken, 14).
-define(spell_aura_damage_shield, 15).
-define(spell_aura_mod_stealth, 16).
-define(spell_aura_mod_stealth_detect, 17).
-define(spell_aura_mod_invisibility, 18).
-define(spell_aura_mod_invisibility_detection, 19).
-define(spell_aura_obs_mod_health, 20).                         % 20,21 unofficial
-define(spell_aura_obs_mod_mana, 21).
-define(spell_aura_mod_resistance, 22).
-define(spell_aura_periodic_trigger_spell, 23).
-define(spell_aura_periodic_energize, 24).
-define(spell_aura_mod_pacify, 25).
-define(spell_aura_mod_root, 26).
-define(spell_aura_mod_silence, 27).
-define(spell_aura_reflect_spells, 28).
-define(spell_aura_mod_stat, 29).
-define(spell_aura_mod_skill, 30).
-define(spell_aura_mod_increase_speed, 31).
-define(spell_aura_mod_increase_mounted_speed, 32).
-define(spell_aura_mod_decrease_speed, 33).
-define(spell_aura_mod_increase_health, 34).
-define(spell_aura_mod_increase_energy, 35).
-define(spell_aura_mod_shapeshift, 36).
-define(spell_aura_effect_immunity, 37).
-define(spell_aura_state_immunity, 38).
-define(spell_aura_school_immunity, 39).
-define(spell_aura_damage_immunity, 40).
-define(spell_aura_dispel_immunity, 41).
-define(spell_aura_proc_trigger_spell, 42).
-define(spell_aura_proc_trigger_damage, 43).
-define(spell_aura_track_creatures, 44).
-define(spell_aura_track_resources, 45).
-define(spell_aura_46, 46).                                     % Ignore all Gear test spells
-define(spell_aura_mod_parry_percent, 47).
-define(spell_aura_48, 48).                                     % One periodic spell
-define(spell_aura_mod_dodge_percent, 49).
-define(spell_aura_mod_block_skill, 50).
-define(spell_aura_mod_block_percent, 51).
-define(spell_aura_mod_crit_percent, 52).
-define(spell_aura_periodic_leech, 53).
-define(spell_aura_mod_hit_chance, 54).
-define(spell_aura_mod_spell_hit_chance, 55).
-define(spell_aura_transform, 56).
-define(spell_aura_mod_spell_crit_chance, 57).
-define(spell_aura_mod_increase_swim_speed, 58).
-define(spell_aura_mod_damage_done_creature, 59).
-define(spell_aura_mod_pacify_silence, 60).
-define(spell_aura_mod_scale, 61).
-define(spell_aura_periodic_health_funnel, 62).
-define(spell_aura_periodic_mana_funnel, 63).
-define(spell_aura_periodic_mana_leech, 64).
-define(spell_aura_mod_casting_speed_not_stack, 65).
-define(spell_aura_feign_death, 66).
-define(spell_aura_mod_disarm, 67).
-define(spell_aura_mod_stalked, 68).
-define(spell_aura_school_absorb, 69).
-define(spell_aura_extra_attacks, 70).
-define(spell_aura_mod_spell_crit_chance_school, 71).
-define(spell_aura_mod_power_cost_school_pct, 72).
-define(spell_aura_mod_power_cost_school, 73).
-define(spell_aura_reflect_spells_school, 74).
-define(spell_aura_mod_language, 75).
-define(spell_aura_far_sight, 76).
-define(spell_aura_mechanic_immunity, 77).
-define(spell_aura_mounted, 78).
-define(spell_aura_mod_damage_percent_done, 79).
-define(spell_aura_mod_percent_stat, 80).
-define(spell_aura_split_damage_pct, 81).
-define(spell_aura_water_breathing, 82).
-define(spell_aura_mod_base_resistance, 83).
-define(spell_aura_mod_regen, 84).
-define(spell_aura_mod_power_regen, 85).
-define(spell_aura_channel_death_item, 86).
-define(spell_aura_mod_damage_percent_taken, 87).
-define(spell_aura_mod_health_regen_percent, 88).
-define(spell_aura_periodic_damage_percent, 89).
-define(spell_aura_mod_resist_chance, 90).
-define(spell_aura_mod_detect_range, 91).
-define(spell_aura_prevents_fleeing, 92).
-define(spell_aura_mod_unattackable, 93).
-define(spell_aura_interrupt_regen, 94).
-define(spell_aura_ghost, 95).
-define(spell_aura_spell_magnet, 96).
-define(spell_aura_mana_shield, 97).
-define(spell_aura_mod_skill_talent, 98).
-define(spell_aura_mod_attack_power, 99).
-define(spell_aura_auras_visible, 100).
-define(spell_aura_mod_resistance_pct, 101).
-define(spell_aura_mod_melee_attack_power_versus, 102).
-define(spell_aura_mod_total_threat, 103).
-define(spell_aura_water_walk, 104).
-define(spell_aura_feather_fall, 105).
-define(spell_aura_hover, 106).
-define(spell_aura_add_flat_modifier, 107).
-define(spell_aura_add_pct_modifier, 108).
-define(spell_aura_add_target_trigger, 109).
-define(spell_aura_mod_power_regen_percent, 110).
-define(spell_aura_add_caster_hit_trigger, 111).
-define(spell_aura_override_class_scripts, 112).
-define(spell_aura_mod_ranged_damage_taken, 113).
-define(spell_aura_mod_ranged_damage_taken_pct, 114).
-define(spell_aura_mod_healing, 115).
-define(spell_aura_mod_regen_during_combat, 116).
-define(spell_aura_mod_mechanic_resistance, 117).
-define(spell_aura_mod_healing_pct, 118).
-define(spell_aura_share_pet_tracking, 119).
-define(spell_aura_untrackable, 120).
-define(spell_aura_empathy, 121).
-define(spell_aura_mod_offhand_damage_pct, 122).
-define(spell_aura_mod_target_resistance, 123).
-define(spell_aura_mod_ranged_attack_power, 124).
-define(spell_aura_mod_melee_damage_taken, 125).
-define(spell_aura_mod_melee_damage_taken_pct, 126).
-define(spell_aura_ranged_attack_power_attacker_bonus, 127).
-define(spell_aura_mod_possess_pet, 128).
-define(spell_aura_mod_speed_always, 129).
-define(spell_aura_mod_mounted_speed_always, 130).
-define(spell_aura_mod_ranged_attack_power_versus, 131).
-define(spell_aura_mod_increase_energy_percent, 132).
-define(spell_aura_mod_increase_health_percent, 133).
-define(spell_aura_mod_mana_regen_interrupt, 134).
-define(spell_aura_mod_healing_done, 135).
-define(spell_aura_mod_healing_done_percent, 136).
-define(spell_aura_mod_total_stat_percentage, 137).
-define(spell_aura_mod_melee_haste, 138).
-define(spell_aura_force_reaction, 139).
-define(spell_aura_mod_ranged_haste, 140).
-define(spell_aura_mod_ranged_ammo_haste, 141).
-define(spell_aura_mod_base_resistance_pct, 142).
-define(spell_aura_mod_resistance_exclusive, 143).
-define(spell_aura_safe_fall, 144).
-define(spell_aura_charisma, 145).
-define(spell_aura_persuaded, 146).
-define(spell_aura_mechanic_immunity_mask, 147).
-define(spell_aura_retain_combo_points, 148).
-define(spell_aura_resist_pushback , 149).                      %    Resist Pushback
-define(spell_aura_mod_shield_blockvalue_pct, 150).
-define(spell_aura_track_stealthed , 151).                      %    Track Stealthed
-define(spell_aura_mod_detected_range, 152).                    %    Mod Detected Range
-define(spell_aura_split_damage_flat, 153).                     %    Split Damage Flat
-define(spell_aura_mod_stealth_level, 154).                     %    Stealth Level Modifier
-define(spell_aura_mod_water_breathing, 155).                   %    Mod Water Breathing
-define(spell_aura_mod_reputation_gain, 156).                   %    Mod Reputation Gain
-define(spell_aura_pet_damage_multi, 157).                      %    Mod Pet Damage
-define(spell_aura_mod_shield_blockvalue, 158).
-define(spell_aura_no_pvp_credit, 159).
-define(spell_aura_mod_aoe_avoidance, 160).                   %/< Reduces the hit chance for AOE spells
-define(spell_aura_mod_health_regen_in_combat, 161).
-define(spell_aura_power_burn_mana, 162).
-define(spell_aura_mod_crit_damage_bonus, 163).
-define(spell_aura_164, 164).
-define(spell_aura_melee_attack_power_attacker_bonus, 165).
-define(spell_aura_mod_attack_power_pct, 166).
-define(spell_aura_mod_ranged_attack_power_pct, 167).
-define(spell_aura_mod_damage_done_versus, 168).
-define(spell_aura_mod_crit_percent_versus, 169).
-define(spell_aura_detect_amore, 170).
-define(spell_aura_mod_speed_not_stack, 171).
-define(spell_aura_mod_mounted_speed_not_stack, 172).
-define(spell_aura_allow_champion_spells, 173).
-define(spell_aura_mod_spell_damage_of_stat_percent, 174).      % in 1.12.1 only dependent spirit case
-define(spell_aura_mod_spell_healing_of_stat_percent, 175).
-define(spell_aura_spirit_of_redemption, 176).
-define(spell_aura_aoe_charm, 177).
-define(spell_aura_mod_debuff_resistance, 178).
-define(spell_aura_mod_attacker_spell_crit_chance, 179).
-define(spell_aura_mod_flat_spell_damage_versus, 180).
-define(spell_aura_mod_flat_spell_crit_damage_versus, 181).     % unused - possible flat spell crit damage versus
-define(spell_aura_mod_resistance_of_stat_percent, 182).
-define(spell_aura_mod_critical_threat, 183).
-define(spell_aura_mod_attacker_melee_hit_chance, 184).
-define(spell_aura_mod_attacker_ranged_hit_chance, 185).
-define(spell_aura_mod_attacker_spell_hit_chance, 186).
-define(spell_aura_mod_attacker_melee_crit_chance, 187).
-define(spell_aura_mod_attacker_ranged_crit_chance, 188).
-define(spell_aura_mod_rating, 189).
-define(spell_aura_mod_faction_reputation_gain, 190).
-define(spell_aura_use_normal_movement_speed, 191).

